### ISSUE TITLE
Contributor photo and topic name alignment need to be corrected under featured projects

### ISSUE THREAD

**Issue by Aswin-Bhupalam-ML** [maplelabs/opensource-portal#1]
Contributor photo and topic name alignment need to be corrected under featured projects. Below is the snapshot:
![image](https://user-images.githubusercontent.com/119499289/205043315-2ce71bd8-4fb0-4c3f-9337-e00839f6aadf.png)

**Comment by Aishik-Mukherjee-ML** [comment]
<img width="1435" alt="image" src="https://user-images.githubusercontent.com/61682898/205208798-2df4ba0a-e8bf-4984-92d2-6d6028ecf7aa.png">

The issue has been fixed and pushed to staging.
